### ISSUE TITLE
View 1 - Choose Asset

### ISSUE THREAD

**Issue by pimato** [OasisDEX/oasis-direct-old#2]
- Contract : **MatchingContract**
https://github.com/makerdao/maker-otc/blob/master/src/matching_market.sol
- Pairs: `W-ETH/MKR` `SAI/MKR` `W-ETH/SAI`
- **No Registration needed** because of Web3.js
- The user will have the chance to select his account via a dropdown menu

## View 1

![od_1_assets](https://user-images.githubusercontent.com/5337809/29119217-7bd43d00-7d2f-11e7-9da8-291579450110.png)

- Left List/Picker indicates the token the user wants to sell
- Right List/Picker indicates the token the user wants to buy.
- The text will change dynamically according what the user has picked.
- With the inputfield the user needs to specify his amount to buy.
- Button `continue` will show `View 2`

**Comment by peculiarity** [comment]
**TODO**

- [x] Integrate React 
- [x] Create reusable components 
- [x] Integrate Redux 
- [ ] Integrate Web3 library
- [ ] Integrate Contract ABI ( Matching Market)
- [x] Introduce Available Assets ( tokens - WETH / SAI / MKR )
- [ ] Submit the new order (proceed to view 2)
